 docker compose config
name: cd
services:
  tomcat1:
    container_name: tomcat1
    image: ':'
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp
    restart: always
  tomcat2:
    container_name: tomcat2
    image: ':'
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8082"
        protocol: tcp
    restart: always
  tomcat3:
    container_name: tomcat3
    image: ':'
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8083"
        protocol: tcp
    restart: always
networks:
  default:
    name: cd_default
[root@ip-172-31-93-150 CD]# docker compose config | grep -n "image:"
5:    image: ':'
16:    image: ':'
27:    image: ':'
